/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    primary: '#6750A4',
    onPrimary: '#FFFFFF',
    backgroundSecondary: '#F1F4F8',
    surface: '#F5F5F5',
    onSurface: '#1C1B1F',
    secondary: '#625B71',
    onSecondary: '#FFFFFF',
    error: '#B3261E',
    onError: '#FFFFFF',
    success: '#0F9D58',
    danger: '#FF3B30',
    divider: 'rgba(0, 0, 0, 0.12)',
    iconColor: '#49454F',
    buttonBackground: '#6750A4',
    buttonText: '#FFFFFF',
    buttonBorder: '#6750A4',
    cell: '#F5F5F5',
    selectedCell: '#EADDFF',
    selectedOverlayColor: '#EADDFF',
    sameValueOverlayColor: '#EADDFF',
    conflictOverlayColor: '#F5B7B1',
    overlayColor: '#E7E0EC',
    cellBorderColor: '#000000',
    settingItemBackground: '#DADADA',
    buttonBlue: '#60a5fa',
    selectedItemBackground: '#D0D0D0',
    itemBorderColor: '#E0E0E0',
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    primary: '#D0BCFF',
    onPrimary: '#381E72',
    backgroundSecondary: '#1C1B1F',
    surface: '#1C1B1F',
    onSurface: '#FFFFFF',
    secondary: '#CCC2DC',
    onSecondary: '#332D41',
    error: '#CF6679',
    onError: '#000000',
    success: '#66BB6A',
    danger: '#CF6679',
    divider: 'rgba(255, 255, 255, 0.12)',
    iconColor: '#E0E0E0',
    buttonBackground: '#D0BCFF',
    buttonText: '#000000',
    buttonBorder: '#D0BCFF',
    cell: '#1C1B1F',
    selectedCell: '#4F378B',
    selectedOverlayColor: '#4F378B',
    sameValueOverlayColor: '#4F378B',
    conflictOverlayColor: '#CF6679',
    overlayColor: '#2B2B2B',
    cellBorderColor: '#FFFFFF',
    settingItemBackground: '#2C2C2C',
    buttonBlue: '#90CAF9',
    selectedItemBackground: '#333333',
    itemBorderColor: '#2E2E2E',
  },
};
