name: Android Internal Github (Killer)

on:
  push:
    branches:
      - master
    paths:
      - 'packages/**'
      - 'apps/killer/android/**'
      - 'apps/killer/app/**'
      - 'apps/killer/assets/**'
      - 'apps/killer/i18n/**'
      - 'apps/killer/theme/**'
      - 'apps/killer/types/**'
      - 'apps/killer/utils/**'

jobs:
  build-ios:
    name: Build and Upload Android to Google Play Console
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if packages/** changed
        id: check-packages
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^packages/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Cancel if packages changed
        if: steps.check-packages.outputs.changed == 'true'
        run: |
          echo "Changes detected in packages/**. Skipping workflow."
          exit 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Decode keystore
        run: |
          echo "$K_ANDROID_KEYSTORE_BASE64" | base64 --decode > apps/killer/android/app/sudoku-key.keystore
          echo "$K_PLAY_STORE_KEY_BASE64" | base64 --decode > apps/killer/android/fastlane/play-store-key.json
        env:
          K_ANDROID_KEYSTORE_BASE64: ${{ secrets.K_ANDROID_KEYSTORE_BASE64 }}
          K_PLAY_STORE_KEY_BASE64: ${{ secrets.K_PLAY_STORE_KEY_BASE64 }}

      - name: Install dependencies
        run: |
          yarn install

      - name: Install fastlane (global)
        run: |
          sudo gem install fastlane
          fastlane --version

      - name: Run Fastlane killer internal_github (Android)
        run: |
          cd apps/killer
          rm -rf node_modules
          ln -s ../../node_modules .
          cd android
          fastlane internal_github
        env:
          APP_PACKAGE_NAME: ${{ secrets.K_APP_PACKAGE_NAME }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.K_UNSPLASH_ACCESS_KEY }}
          AD_UNIT_BANNER_ANDROID: ${{ secrets.K_AD_UNIT_BANNER_ANDROID }}
          AD_UNIT_INTERSTITIAL_ANDROID: ${{ secrets.K_AD_UNIT_INTERSTITIAL_ANDROID }}
          AD_UNIT_REWARDED_ANDROID: ${{ secrets.K_AD_UNIT_REWARDED_ANDROID }}
          AD_UNIT_REWARDED_I_ANDROID: ${{ secrets.K_AD_UNIT_REWARDED_I_ANDROID }}
          AD_UNIT_BANNER_IOS: ${{ secrets.K_AD_UNIT_BANNER_IOS }}
          AD_UNIT_INTERSTITIAL_IOS: ${{ secrets.K_AD_UNIT_INTERSTITIAL_IOS }}
          AD_UNIT_REWARDED_IOS: ${{ secrets.K_AD_UNIT_REWARDED_IOS }}
          AD_UNIT_REWARDED_I_IOS: ${{ secrets.K_AD_UNIT_REWARDED_I_IOS }}
