name: iOS Beta Github (Killer)

on:
  push:
    branches:
      - master
    paths:
      - 'apps/killer/ios/**'
      - 'apps/killer/app/**'
      - 'apps/killer/assets/**'
      - 'apps/killer/i18n/**'
      - 'apps/killer/theme/**'
      - 'apps/killer/types/**'
      - 'apps/killer/utils/**'

jobs:
  check-changes:
    name: Check Code Changes
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Determine diff range
        id: sha-range
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "base_sha=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
            echo "head_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "base_sha=${{ github.event.before }}" >> $GITHUB_OUTPUT
            echo "head_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Get changed files
        id: get-changes
        run: |
          changed_files=$(git diff --name-only ${{ steps.sha-range.outputs.base_sha }} ${{ steps.sha-range.outputs.head_sha }})
          echo "$changed_files" > changed.txt
          echo "Changed files:"
          cat changed.txt

      - name: Check affected paths
        id: filter
        run: |
          if grep -q '^packages/' changed.txt; then
            echo "Changes in packages/** detected → skip workflow"
            echo "should_run=false" >> $GITHUB_OUTPUT
          elif grep -qE '^(apps/killer/)' changed.txt; then
            echo "Changes in apps/killer/** → continue"
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant changes → skip"
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  build:
    name: Run Killer Build
    needs: check-changes
    if: needs.check-changes.outputs.should_run == 'true'
    runs-on: macos-14
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if packages/** changed
        id: check-packages
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^packages/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Cancel if packages changed
        if: steps.check-packages.outputs.changed == 'true'
        run: |
          echo "Changes detected in packages/**. Skipping workflow."
          exit 0

      - name: Setup SSH key for GitHub
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_KEY }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          yarn install
          cd apps/killer/ios && pod install

      - name: Restore AuthKey from base64
        run: |
          echo "$K_APP_STORE_CONNECT_API_KEY_BASE64" | base64 -d > apps/killer/ios/fastlane/AuthKey.p8
        env:
          K_APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.K_APP_STORE_CONNECT_API_KEY_BASE64 }}

      - name: Install fastlane (global)
        run: |
          sudo gem install fastlane
          fastlane --version

      - name: Run Fastlane killer beta_github (iOS)
        run: |
          cd apps/killer/ios
          fastlane beta_github
        env:
          IDEDisableFileSyncMonitor: 'YES'
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_VARIANT: 'killer'
          UNSPLASH_ACCESS_KEY: ${{ secrets.K_UNSPLASH_ACCESS_KEY }}
          AD_APP_ID_ANDROID: ${{ secrets.K_AD_APP_ID_ANDROID }}
          AD_UNIT_BANNER_ANDROID: ${{ secrets.K_AD_UNIT_BANNER_ANDROID }}
          AD_UNIT_INTERSTITIAL_ANDROID: ${{ secrets.K_AD_UNIT_INTERSTITIAL_ANDROID }}
          AD_UNIT_REWARDED_ANDROID: ${{ secrets.K_AD_UNIT_REWARDED_ANDROID }}
          AD_UNIT_REWARDED_I_ANDROID: ${{ secrets.K_AD_UNIT_REWARDED_I_ANDROID }}
          AD_APP_ID_IOS: ${{ secrets.K_AD_APP_ID_IOS }}
          AD_UNIT_BANNER_IOS: ${{ secrets.K_AD_UNIT_BANNER_IOS }}
          AD_UNIT_INTERSTITIAL_IOS: ${{ secrets.K_AD_UNIT_INTERSTITIAL_IOS }}
          AD_UNIT_REWARDED_IOS: ${{ secrets.K_AD_UNIT_REWARDED_IOS }}
          AD_UNIT_REWARDED_I_IOS: ${{ secrets.K_AD_UNIT_REWARDED_I_IOS }}
