name: iOS Beta Github (Classic)

on:
  push:
    branches:
      - master
    paths:
      - 'packages/**'
      - 'apps/classic/ios/**'
      - 'apps/classic/app/**'
      - 'apps/classic/assets/**'
      - 'apps/classic/i18n/**'
      - 'apps/classic/theme/**'
      - 'apps/classic/types/**'
      - 'apps/classic/utils/**'
      - 'apps/classic/app.config.ts'

jobs:
  build-ios:
    name: Build and Upload iOS to TestFlight
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if packages/** changed
        id: check-packages
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^packages/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Cancel if packages changed
        if: steps.check-packages.outputs.changed == 'true'
        run: |
          echo "Changes detected in packages/**. Skipping workflow."
          exit 0

      - name: Setup SSH key for GitHub
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_KEY }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          yarn install
          cd apps/classic/ios && pod install

      - name: Restore AuthKey from base64
        run: |
          echo "$C_APP_STORE_CONNECT_API_KEY_BASE64" | base64 -d > apps/classic/ios/fastlane/AuthKey.p8
        env:
          C_APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.C_APP_STORE_CONNECT_API_KEY_BASE64 }}

      - name: Install fastlane (global)
        run: |
          sudo gem install fastlane
          fastlane --version

      - name: Run Fastlane classic beta_github (iOS)
        run: |
          cd apps/classic/ios
          fastlane beta_github
        env:
          IDEDisableFileSyncMonitor: 'YES'
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.C_UNSPLASH_ACCESS_KEY }}
          AD_APP_ID_ANDROID: ${{ secrets.C_AD_APP_ID_ANDROID }}
          AD_UNIT_BANNER_ANDROID: ${{ secrets.C_AD_UNIT_BANNER_ANDROID }}
          AD_UNIT_INTERSTITIAL_ANDROID: ${{ secrets.C_AD_UNIT_INTERSTITIAL_ANDROID }}
          AD_UNIT_REWARDED_ANDROID: ${{ secrets.C_AD_UNIT_REWARDED_ANDROID }}
          AD_UNIT_REWARDED_I_ANDROID: ${{ secrets.C_AD_UNIT_REWARDED_I_ANDROID }}
          AD_APP_ID_IOS: ${{ secrets.C_AD_APP_ID_IOS }}
          AD_UNIT_BANNER_IOS: ${{ secrets.C_AD_UNIT_BANNER_IOS }}
          AD_UNIT_INTERSTITIAL_IOS: ${{ secrets.C_AD_UNIT_INTERSTITIAL_IOS }}
          AD_UNIT_REWARDED_IOS: ${{ secrets.C_AD_UNIT_REWARDED_IOS }}
          AD_UNIT_REWARDED_I_IOS: ${{ secrets.C_AD_UNIT_REWARDED_I_IOS }}
